openapi: 3.1.0
info:
  title: Auth API
  description: Authentication API using AWS Cognito
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Development server

paths:
  /signup/login:
    post:
      summary: Sign up with username and password
      description: Creates a new user account using username and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
                - type
              properties:
                username:
                  type: string
                  description: User's username or email address
                password:
                  type: string
                  format: password
                  description: User's password
                type:
                  type: string
                  description: Type of identifier (e.g. email, phone_number)
                  example: "email"
      responses:
        '201':
          description: User successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User created successfully"
                  code_delivery:
                    type: object
                    properties:
                      type:
                        type: string
                        description: The medium through which the confirmation code was sent (lowercase)
                        example: "email"
                      destination:
                        type: string
                        description: The destination where the code was sent (lowercase, partially masked)
                        example: "j***@e***"
                  user_confirmed:
                    type: boolean
                    description: Whether the user is already confirmed or needs confirmation
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message from Cognito
        '500':
          description: HTTP request error or unexpected server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal Server Error"

  /signup/social/{provider}:
    get:
      summary: Redirects to OAuth registration flow
      description: Redirects the user to the selected identity provider registration page
      parameters:
        - in: path
          name: provider
          required: true
          schema:
            type: string
          description: Identity provider name (e.g. google, microsoft)
      responses:
        '302':
          description: Redirect to Cognito OAuth flow
          headers:
            Location:
              schema:
                type: string
              description: Cognito OAuth authorize URL with provider, redirect URI, client ID and scopes (openid, email, profile)
              example: "https://domain.com/oauth2/authorize?identity_provider=Google&redirect_uri=http%3A//localhost%3A3001/callback&response_type=code&client_id=client123&scope=openid+email+profile"
        '400':
          description: Invalid or missing provider
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid provider"

  /forgot:
    post:
      summary: Initiate password reset
      description: Initiates the password reset process by sending a confirmation code to the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
              properties:
                username:
                  type: string
                  description: User's username or email
      responses:
        '200':
          description: Reset code sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  delivery_medium:
                    type: string
                    description: The medium used to send the code (e.g. email, sms)
                    example: "email"
                  destination:
                    type: string
                    description: The masked destination where the code was sent
                    example: "j***@e***"
        '400':
          description: Invalid username or user not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message from Cognito
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal Server Error"

  /forgot/confirm:
    post:
      summary: Confirm password reset
      description: Confirms the password reset using the confirmation code and sets the new password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - confirmation_code
                - password
              properties:
                username:
                  type: string
                  description: User's username or email
                confirmation_code:
                  type: string
                  description: The confirmation code sent to the user
                password:
                  type: string
                  format: password
                  description: The new password to set
      responses:
        '200':
          description: Password successfully reset
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Password reset successfully"
        '400':
          description: Invalid code or password requirements not met
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message from Cognito
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal Server Error"

  /signin:
    post:
      summary: User authentication
      description: Authenticates user using credentials via AWS Cognito using USER_PASSWORD_AUTH flow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: User's username or email
                password:
                  type: string
                  format: password
                  description: User's password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Access token from Cognito
                  token_type:
                    type: string
                    description: Type of the token (e.g. Bearer)
        '400':
          description: Invalid credentials or user not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message from Cognito
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal Server Error"

  /confirm:
    post:
      summary: Confirm user signup
      description: Confirms a user's registration using the confirmation code sent to their destination (e.g., email, SMS or other)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - confirmation_code
              properties:
                username:
                  type: string
                  description: The username of the user to confirm
                confirmation_code:
                  type: string
                  description: Confirmation code sent to the user
      responses:
        '200':
          description: User confirmed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User confirmed successfully"
        '400':
          description: Invalid confirmation code or email
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message from Cognito
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal Server Error"


  /callback:
    get:
      summary: OAuth flow callback
      description: Callback endpoint to process OAuth flow return
      parameters:
        - in: query
          name: code
          schema:
            type: string
          description: Authorization code returned by OAuth provider
        - in: query
          name: error
          schema:
            type: string
          description: Error returned by OAuth provider (if any)
        - in: query
          name: error_description
          schema:
            type: string
          description: Description of the returned error (if any)
      responses:
        '302':
          description: Redirect after callback processing
          headers:
            Location:
              schema:
                type: string
              description: Redirect URL with token or error
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
      required:
        - message
    
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          description: Success message
      required:
        - message

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Token issued by AWS Cognito
