name: tarrpc-client
modules:
  - module: tarrpc
    with:
      host: localhost
      port: 8080
      service_name: example_service
      transport: tcp
      timeout: 30
      retry_attempts: 3

steps:
  - step: health_check
    description: "Check if the RPC server is healthy"
    use: tarrpc
    input:
      method: health_check
    
  - step: get_service_info
    description: "Get information about the RPC service"
    use: tarrpc
    input:
      method: get_service_info
    
  - step: process_data_call
    description: "Call the process_data RPC method"
    use: tarrpc
    input:
      method: process_data
      args:
        data: "sample data to process"
        options:
          priority: high
          batch_size: 100
      timeout: 15
      
  - step: calculate_call
    description: "Call the calculate RPC method"
    use: tarrpc
    input:
      method: calculate
      args:
        operation: "sum"
        values: [1, 2, 3, 4, 5]
      context:
        user_id: "user123"
        session_id: "session456"
        
  - step: transform_call
    description: "Call the transform RPC method"
    use: tarrpc
    input:
      method: transform
      args:
        input: "Hello, World!"
        format: "uppercase"
      timeout: 10
      
  - step: log_results
    description: "Log the results of all RPC calls"
    use: log
    input:
      level: info
      message: "All RPC calls completed successfully"
