# Configuration for tarrpc module
server:
  host: localhost
  port: 8080
  service_name: phlow_tarrpc_service
  transport: tcp
  timeout: 30
  max_connections: 100
  retry_attempts: 3

client:
  host: localhost
  port: 8080
  service_name: phlow_tarrpc_service
  transport: tcp
  timeout: 30
  retry_attempts: 3

# Example methods that can be exposed by the server
methods:
  - name: process_data
    handler: process_data_handler
    description: "Process incoming data with custom logic"
    
  - name: calculate
    handler: calculate_handler
    description: "Perform mathematical calculations"
    
  - name: transform
    handler: transform_handler
    description: "Transform data from one format to another"
    
  - name: validate
    handler: validate_handler
    description: "Validate input data against schema"
    
  - name: aggregate
    handler: aggregate_handler
    description: "Aggregate multiple data points"

# Transport options
transports:
  tcp:
    description: "TCP transport for network communication"
    use_case: "Production deployments, distributed systems"
    
  memory:
    description: "In-memory transport for same-process communication"
    use_case: "Testing, local development, embedded systems"
