[tasks.build-modules]
workspace = false
description = "Executa o script build.sh"
script = ["chmod +x ./scripts/modules-build.sh", "./scripts/modules-build.sh"]

[tasks.build-bin]
workspace = false
description = "Executa o script"
script = ["cargo", "build", "--release", "-p", "phlow-runtime"]

[tasks.packages]
workspace = false
description = "Empacota todos os módulos em ./modules"
script = ["chmod +x ./scripts/packages.sh", "./scripts/packages.sh"]

[tasks.env-build]
workspace = false
description = "Executa o container Docker phlow-environment"
script = [
    "docker build --target environment -t phlow-env -f ./docker/Dockerfile .",
]
args = []

[tasks.env]
workspace = false
description = "Executa o container Docker phlow-environment"
script = ["docker run -it --rm -v .:/app phlow-env ${@}"]
