[tasks.build-bin]
workspace = false
description = "Executa o script"
script = ["cargo build --release -p phlow-runtime"]

[tasks.packages]
workspace = false
description = "Empacota todos os módulos em ./modules"
script = ["chmod +x ./scripts/packages.sh", "./scripts/packages.sh"]

[tasks.env-build]
workspace = false
description = "Executa o container Docker phlow-environment"
script = [
    "docker build --target environment -t phlow-env -f ./docker/Dockerfile .",
]
args = []

[tasks.env]
workspace = false
description = "Executa o container Docker phlow-environment"
script = ["docker run -it --rm -v .:/app phlow-env ${@}"]

[tasks.example]
workspace = false
description = "Executa cargo run -p phlow-runtime -- examples/ARG"
script = ["cargo run -p phlow-runtime -- examples/${@}"]
args = []

[tasks.local]
workspace = false
description = "Executa ./scripts/local-packages.sh ARG"
script = [
    "chmod +x ./scripts/local-packages.sh",
    "./scripts/local-packages.sh ${@}",
]
args = []

[tasks.install_local]
workspace = false
description = "Compila o phlow-runtime, remove o binário antigo e copia o novo para ~/.phlow/phlow"
script = [
    "cargo build --release -p phlow-runtime",
    "rm -f ~/.phlow/phlow",
    "mkdir -p ~/.phlow",
    "cp ./target/release/phlow ~/.phlow/phlow",
]
