module: amqp
version: latest
with:
  routing_key: "my.routing.key"
  exchange: my.exchange
  queue_name: "my.queue"
  exchange_type: direct
  declare: true
  auto_bind: true
  queue_durable: true
  exchange_durable: true
  queue_exclusive: false
  queue_auto_delete: false
