###########################
# Final image: glibc slim
# docker build --target phlow-slim -t phlow:slim -f Dockerfile.multi .
###########################
FROM debian:bullseye-slim AS phlow-slim

ENV PHLOW_MAIN="https://github.com/lowcarboncode/phlow-mirror-request/tarball/main"
ENV PHLOW_LOG="info"
ENV PHLOW_OTEL="true"

# Espera que o binário já esteja disponível no contexto de build
COPY phlow-x86_64-unknown-linux-gnu /phlow
ENTRYPOINT ["/phlow"]
