use crate::{setup::Config, RPC};
use futures::{future, prelude::*};
use phlow_sdk::prelude::*;
use std::net::SocketAddr;
use tarpc::{
    context,
    server::{self, incoming::Incoming, Channel},
    tokio_serde::formats::Json,
};

#[derive(Clone)]
struct RPCServer(SocketAddr);

impl RPC for RPCServer {
    async fn call(self, _: context::Context, name: Value) -> Value {
        format!("Hello, {}!", name.to_string()).to_value()
    }
}

async fn spawn(fut: impl Future<Output = ()> + Send + 'static) {
    tokio::spawn(fut);
}

pub async fn main(config: Config) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let mut listener =
        tarpc::serde_transport::tcp::listen(&config.main_server.get_address(), Json::default)
            .await?;

    listener.config_mut().max_frame_length(usize::MAX);
    listener
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        // Limit channels to 1 per IP.
        .max_channels_per_key(config.parallel_executions, |t| {
            t.transport().peer_addr().unwrap().ip()
        })
        // serve is generated by the service attribute. It takes as input any type implementing
        // the generated World trait.
        .map(|channel| {
            let server = RPCServer(channel.transport().peer_addr().unwrap());
            channel.execute(server.serve()).for_each(spawn)
        })
        // Max 10 channels.
        .buffer_unordered(config.parallel_executions as usize)
        .for_each(|_| async {})
        .await;

    Ok(())
}
