name: Build Binary using Docker
description: Build the binary inside a Docker container and export it to the GitHub workspace.

inputs:
  dockerfile:
    description: Path to Dockerfile
    required: true
  target:
    description: Docker build target stage
    required: true
  output_path:
    description: Path inside container to the built binary
    required: true
  filename:
    description: Final filename after extraction
    required: true

runs:
  using: composite
  steps:
    - name: Build Docker Image
      run: |
        docker build -f ${{ inputs.dockerfile }} --target ${{ inputs.target }} -t phlow-build-temp .
      shell: bash

    - name: Extract Binary
      run: |
        docker run --rm -v ${{ github.workspace }}:/app phlow-build-temp cp ${{ inputs.output_path }} /app/${{ inputs.filename }}
      shell: bash
