openapi: 3.1.0
info:
  title: "Test API"
  version: "1.0.0"
paths:
  /users:
    get:
      summary: "List all users"
      responses:
        200:
          description: "A list of users"
    post:
      summary: "Create a new user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
              additionalProperties: true # Permite propriedades adicionais
              properties:
                name:
                  type: string
                  minLength: 2
                  maxLength: 50
                  pattern: '^[a-zA-ZÀ-ÿ\s]+$' # Apenas letras e espaços
                email:
                  type: string
                  format: email # Validação built-in de email
                  pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$' # Regex customizado adicional
                age:
                  type: integer
                  minimum: 0
                  maximum: 120
                  description: "User age in years (optional)"
                phone:
                  type: string
                  pattern: '^\+?[1-9]\d{1,14}$' # Formato internacional de telefone (opcional)
                  description: "User phone number (optional)"
      responses:
        201:
          description: "User created"
  /users/{userId}:
    get:
      summary: "Get user by ID"
      responses:
        200:
          description: "User found"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
    delete:
      summary: "Delete user by ID"
      responses:
        204:
          description: "User deleted"
          content: {}
    put:
      summary: "Update user by ID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
              properties:
                name:
                  type: string
                  minLength: 2
                  maxLength: 50
                  pattern: '^[a-zA-ZÀ-ÿ\s]+$'
                age:
                  type: integer
                  minimum: 0
                  maximum: 120
                phone:
                  type: string
                  pattern: '^\+?[1-9]\d{1,14}$'
      responses:
        200:
          description: "User updated"
