openapi: 3.1.0
info:
  title: "Test API"
  version: "1.0.0"
paths:
  /users:
    get:
      summary: "List all users"
      responses:
        200:
          description: "A list of users"
    post:
      summary: "Create a new user"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        201:
          description: "User created"
  /users/{userId}:
    get:
      summary: "Get user by ID"
      responses:
        200:
          description: "User found"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
    delete:
      summary: "Delete user by ID"
      responses:
        204:
          description: "User deleted"
          content: {}
    put:
      summary: "Update user by ID"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        200:
          description: "User updated"
