name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instala Node.js
        uses: actions/setup-node@v4

      - name: Go to phlow-docs
        run: cd phlow-docs

      - name: Instala dependências
        run: npm install

      - name: Build do site
        run: npm run build

      - name: Deploy para GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx docusaurus deploy
