name: Tag, Build, Release, GHCR & Docker Hub

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  tag:
    name: Create Git Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      tag: ${{ steps.get_version.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from Cargo.toml
        id: get_version
        run: |
          version=$(grep '^version' Cargo.toml | head -n1 | sed -E 's/version = "(.*)"/\1/')
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_OUTPUT
      
          if [[ "$version" == *"-nightly"* || "$version" == *"-dev"* ]]; then
            today=$(date +'%Y%m%d')
            tag="nightly-$today"
          else
            tag="v$version"
          fi

          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "TAG=$tag" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$TAG"
          git push origin "$TAG"
        

  build:
    name: Compile Binary
    runs-on: ubuntu-latest
    needs: tag
    outputs:
      version: ${{ needs.tag.outputs.version }}
      tag: ${{ needs.tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cross
        run: cargo install cross

      - name: Build with cross
        run: cross build --release --target x86_64-unknown-linux-gnu -p phlow-runtime

      - name: Rename binary
        run: mv ./target/x86_64-unknown-linux-gnu/release/phlow ./phlow-x86_64-unknown-linux-gnu

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: phlow-x86_64-unknown-linux-gnu
          path: ./phlow-x86_64-unknown-linux-gnu

  release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download gnu binary
        uses: actions/download-artifact@v4
        with:
          name: phlow-x86_64-unknown-linux-gnu
          path: .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build.outputs.tag }}
          name: Release ${{ needs.build.outputs.tag }}
          files: ./phlow-x86_64-unknown-linux-gnu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-ghcr:
    name: Push to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download gnu binary
        uses: actions/download-artifact@v4
        with:
          name: phlow-x86_64-unknown-linux-gnu
          path: .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker images to GHCR
        run: |
          if [[ "${{ needs.build.outputs.tag }}" == nightly-* ]]; then
            docker build -f ./docker/Dockerfile.multi --target phlow \
              -t ghcr.io/${{ github.repository_owner }}/phlow:nightly-glibc \
              -t ghcr.io/${{ github.repository_owner }}/phlow:nightly \
              -t ghcr.io/${{ github.repository_owner }}/phlow:${{ needs.build.outputs.tag }} .
            docker push ghcr.io/${{ github.repository_owner }}/phlow:${{ needs.build.outputs.tag }}
          else
            docker build -f ./docker/Dockerfile.multi --target phlow \
              -t ghcr.io/${{ github.repository_owner }}/phlow:glibc \
              -t ghcr.io/${{ github.repository_owner }}/phlow:busybox \
              -t ghcr.io/${{ github.repository_owner }}/phlow:latest \
              -t ghcr.io/${{ github.repository_owner }}/phlow:${{ needs.build.outputs.tag }} .
            docker push ghcr.io/${{ github.repository_owner }}/phlow:glibc
            docker push ghcr.io/${{ github.repository_owner }}/phlow:busybox
            docker push ghcr.io/${{ github.repository_owner }}/phlow:latest
            docker push ghcr.io/${{ github.repository_owner }}/phlow:${{ needs.build.outputs.tag }}
          fi
      
  docker-hub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download gnu binary
        uses: actions/download-artifact@v4
        with:
          name: phlow-x86_64-unknown-linux-gnu
          path: .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u lowcarboncode --password-stdin

      - name: Build and Push Docker images to Docker Hub
        env:
          DOCKER_BUILDKIT: 1
        run: |
          if [[ "${{ needs.build.outputs.tag }}" == nightly-* ]]; then
            docker build -f ./docker/Dockerfile --target phlow \
              -t lowcarboncode/phlow:nightly-glibc \
              -t lowcarboncode/phlow:nightly \
              -t lowcarboncode/phlow:${{ needs.build.outputs.tag }} .
            docker push lowcarboncode/phlow:${{ needs.build.outputs.tag }}
          else
            docker build -f ./docker/Dockerfile --target phlow \
              -t lowcarboncode/phlow:glibc \
              -t lowcarboncode/phlow:busybox \
              -t lowcarboncode/phlow:latest \
              -t lowcarboncode/phlow:${{ needs.build.outputs.tag }} .
            docker push lowcarboncode/phlow:glibc
            docker push lowcarboncode/phlow:busybox
            docker push lowcarboncode/phlow:latest
            docker push lowcarboncode/phlow:${{ needs.build.outputs.tag }}
          fi
      
