name: Tag, Build, Release, GHCR & Docker Hub

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  tag:
    name: Create Git Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from Cargo.toml
        id: get_version
        run: |
          version=$(grep '^version' Cargo.toml | head -n1 | sed -E 's/version = "(.*)"/\1/')
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "v$VERSION"
          git push origin "v$VERSION"

  build:
    name: Compile Binary
    runs-on: ubuntu-latest
    needs: tag
    outputs:
      version: ${{ needs.tag.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build binary
        run: cargo build --release -p phlow-runtime

      - name: Rename binary
        run: mv ./target/release/phlow ./phlow

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: phlow-binary
          path: ./phlow

  release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: phlow-binary
          path: .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: Release v${{ needs.build.outputs.version }}
          files: ./phlow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-ghcr:
    name: Push to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: phlow-binary
          path: .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker image to GHCR
        run: |
          docker build -f ./docker/Dockerfile \
            -t ghcr.io/${{ github.repository_owner }}/phlow:${{ needs.build.outputs.version }} \
            -t ghcr.io/${{ github.repository_owner }}/phlow:latest .
          docker push ghcr.io/${{ github.repository_owner }}/phlow:${{ needs.build.outputs.version }}
          docker push ghcr.io/${{ github.repository_owner }}/phlow:latest

  docker-hub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: phlow-binary
          path: .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u lowcarboncode --password-stdin

      - name: Build and Push Docker image to Docker Hub
        run: |
          docker build -f ./docker/Dockerfile \
            -t lowcarboncode/phlow:${{ needs.build.outputs.version }} \
            -t lowcarboncode/phlow:latest .
          docker push lowcarboncode/phlow:${{ needs.build.outputs.version }}
          docker push lowcarboncode/phlow:latest
