name: Tagging and Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  tag:
    name: Tag, Build Binary and Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure Rust toolchain is installed
        run: rustup show

      - name: Read version from phlow-runtime/Cargo.toml
        id: get_version
        run: |
          version=$(grep '^version' Cargo.toml | head -n1 | sed -E 's/version = "(.*)"/\1/')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "v$VERSION"
          git push origin "v$VERSION"

      - name: Build binary
        run: cargo build --release -p phlow-runtime

      - name: Rename binary for upload
        run: mv ./target/release/phlow ./phlow

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: ./phlow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -f ./docker/Dockerfile \
            -t ghcr.io/${{ github.repository_owner }}/phlow:${{ env.VERSION }} \
            -t ghcr.io/${{ github.repository_owner }}/phlow:latest .

      - name: Push Docker image with version
        run: docker push ghcr.io/${{ github.repository_owner }}/phlow:${{ env.VERSION }}

      - name: Push Docker image with latest
        run: docker push ghcr.io/${{ github.repository_owner }}/phlow:latest
