name: Release Stable Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'stable-*'

permissions:
  contents: write
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build_docker:
    name: Build Docker Multi-Platform and Export Linux Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version By Tag
        id: get_version
        run: |
          version=$(echo "${GITHUB_REF#refs/tags/}" | sed -E 's/^stable-//')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.cross.gnu
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/phlow:latest
            ghcr.io/${{ github.repository_owner }}/phlow:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/phlow:${{ steps.get_version.outputs.version }}
